import{i as a,S as L}from"./assets/vendor-B07T6_gy.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const v="48292136-dc008af678147f60b21a3f0d6",P="https://pixabay.com/api/";function S(i){const o=new URLSearchParams({key:v,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:21}),n=`${P}?${o.toString()}`;return fetch(n).then(r=>{if(!r.ok)throw new Error("Failed to fetch images.");return r.json()}).then(r=>r.hits.length===0?(a.error({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",titleColor:"#000000",messageColor:"#000000",position:"topRight",backgroundColor:"#FFFF00"}),[]):r.hits).catch(r=>{a.error({title:"Error",message:"An error occurred while fetching data.",titleColor:"#000000",messageColor:"#000000",position:"topRight",backgroundColor:"#FFFF00"})})}const d=document.querySelector(".gallerylist");function w(i){const o=i.map(({webformatURL:n,largeImageURL:r,tags:e,likes:t,views:s,comments:b,downloads:F})=>`
        <div class="gallery-item">
            <a href="${r}">
                <img class="gallery-image" src="${n}" alt="${e}" width="360" height="200"/>
            </a>
            <div class="info">
                <p class="info-text"><b class="info-rating">Likes:</b> ${t}</p>
                <p class="info-text"><b class="info-rating">Views:</b> ${s}</p>
                <p class="info-text"><b class="info-rating">Comments:</b> ${b}</p>
                <p class="info-text"><b class="info-rating">Downloads:</b> ${F}</p>
            </div>
        </div>
    `).join("");d.innerHTML="",d.insertAdjacentHTML("beforeend",o)}const p=document.querySelector(".search-form"),x=document.querySelector(".search-form input"),h=document.querySelector(".loader");let c;p.addEventListener("submit",q);function q(i){i.preventDefault();const o=x.value.trim();if(o==="")return a.info({position:"topRight",title:"Error",message:"Please enter a search query."});A(),S(o).then(n=>{n&&n.length>0&&(w(n),c?c.refresh():c=new L(".gallery-item a",{captionsData:"alt",captionDelay:250}))}).catch(n=>{a.error({position:"topRight",title:"Error",message:"An error occurred. Please try again!",backgroundColor:"#FFFF00"})}).finally(()=>{E(),p.reset()})}function A(){h.style.display="block"}function E(){h.style.display="none"}const u=document.querySelector(".search-form input"),f=["Search images...","car","cat","room","books","forest","garden","space"];let l=0,m;function g(){u.setAttribute("placeholder",f[l]),l=(l+1)%f.length}function y(){m=setInterval(g,2e3)}function $(){clearInterval(m)}u.addEventListener("focus",$);u.addEventListener("blur",y);g();y();
//# sourceMappingURL=index.js.map
