import{a as x,i as l,S as w}from"./assets/vendor-CSTHH2rc.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const E="48292136-dc008af678147f60b21a3f0d6",A="https://pixabay.com/api/";async function h(t,o=1,a=15){try{const n={key:E,q:t,image_type:"photo",titleColor:"#000000",messageColor:"#000000",orientation:"horizontal",safesearch:!0,per_page:a,page:o},{data:e}=await x.get(A,{params:n});return e.hits.length===0?(l.error({title:"No Results",message:"No images match your query. Please try again.",titleColor:"#000000",messageColor:"#000000",position:"topRight",backgroundColor:"#FFFF00"}),{images:[],totalHits:0}):{images:e.hits,totalHits:e.totalHits}}catch(n){throw l.error({title:"Error",message:"Failed to fetch data.",position:"topRight",backgroundColor:"#FF0000"}),n}}const R=document.querySelector(".gallerylist");function p(t){const o=t.map(({webformatURL:a,largeImageURL:n,tags:e,likes:r,views:s,comments:C,downloads:q})=>`
        <div class="gallery-item">
            <a href="${n}">
                <img class="gallery-image" src="${a}" alt="${e}" width="360" height="200"/>
            </a>
            <div class="info">
                <p class="info-text"><b>Likes:</b> ${r}</p>
                <p class="info-text"><b>Views:</b> ${s}</p>
                <p class="info-text"><b>Comments:</b> ${C}</p>
                <p class="info-text"><b>Downloads:</b> ${q}</p>
            </div>
        </div>
    `).join("");R.insertAdjacentHTML("beforeend",o)}const y=document.querySelector(".search-form"),H=document.querySelector(".search-form input"),k=document.querySelector(".loader"),i=document.createElement("button");i.className="load-more-btn";i.textContent="Load more";i.style.display="none";document.querySelector(".gallery-container").appendChild(i);let c=1,g="",b=0;const S=new w(".gallery-item a",{captionsData:"alt",captionDelay:250});y.addEventListener("submit",I);async function I(t){t.preventDefault();const o=H.value.trim();if(o==="")return l.info({position:"topRight",title:"Error",message:"Please enter a search query."});g=o,c=1,$(),u(!0);try{const{images:a,totalHits:n}=await h(g,c);b=n,a.length>0&&(p(a),S.refresh(),F(a.length))}catch{l.error({position:"topRight",title:"Error",message:"An error occurred. Please try again!",backgroundColor:"#FFFF00"})}finally{u(!1),y.reset()}}i.addEventListener("click",async()=>{c++,u(!0);try{const{images:t}=await h(g,c);p(t),S.refresh(),F(t.length),N()}catch{l.error({position:"topRight",title:"Error",message:"An error occurred. Please try again!",backgroundColor:"#FFFF00"})}finally{u(!1)}});function u(t){k.style.display=t?"block":"none"}function F(t){i.style.display=t>0&&b>c*15?"block":"none"}function $(){document.querySelector(".gallerylist").innerHTML=""}function N(){const t=document.querySelector(".gallerylist .gallery-item");if(!t)return;const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}const m=document.querySelector(".search-form input"),f=["S","Se","Sea","Sear","Searc","Search ","Search i","Search im","Search ima","Search imag","Search image","Search images","Search images.","Search images..","Search images...","c","ca","cat","b","bo","boo","book","books","r","ro","roo","room","f","fo","for","fore","fores","forest","g","ga","gar","gard","garde","garden","s","sp","spac","space"];let d=0,L;function v(){m.setAttribute("placeholder",f[d]),d=(d+1)%f.length}function P(){L=setInterval(v,365)}function O(){clearInterval(L)}m.addEventListener("focus",O);m.addEventListener("blur",P);v();P();
//# sourceMappingURL=index.js.map
